(()=>{
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,scenes=[...document.querySelectorAll('.scene')],actor=document.getElementById('catActor'),bar=document.getElementById('progressBar'),rail=document.getElementById('rail');
 const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),ease=t=>1-Math.pow(1-t,3);let current=scrollY,target=scrollY,raf=0,last=-1,partySeen=false;
 scenes.forEach((s,i)=>{const b=document.createElement('button');b.type='button';b.setAttribute('aria-label',`Go to chapter ${i+1}`);b.onclick=()=>s.scrollIntoView({behavior:reduced?'auto':'smooth'});rail.appendChild(b)});const dots=[...rail.children];
 function prog(s,y){const t=s.offsetTop,d=Math.max(1,s.offsetHeight-innerHeight);return clamp((y-t)/d)}
 function setActor(active,p){const mobile=innerWidth<900;let x=0,y=0,r=0,scale=1,opacity=1;const pose=scenes[active]?.dataset.pose||'peek';actor.className=`cat-stage pose-${pose}`;
  if(!mobile){const pts=[[310,215],[260,185],[300,170],[275,120],[-275,70],[270,185],[300,150],[285,125]];[x,y]=pts[active]||[0,0];x+=(p-.5)*55;y+=Math.sin(p*Math.PI)*-18;}
  else{const pts=[[0,205],[0,205],[20,220],[70,190],[-25,30],[20,230],[35,225],[65,205]];[x,y]=pts[active]||[0,0];x+=(p-.5)*25;}
  if(active===4)r=(p-.5)*8;if(active===2)r=-4+p*7;if(active===3)scale=.9+p*.08;if(active===7)scale=.88+p*.05;
  actor.style.setProperty('--sx',x+'px');actor.style.setProperty('--sy',y+'px');actor.style.setProperty('--sr',r+'deg');actor.style.setProperty('--ss',scale);actor.style.setProperty('--catOpacity',opacity);
 }
 function update(){target=scrollY;current=reduced?target:current+(target-current)*.13;bar.style.transform=`scaleX(${clamp(current/Math.max(1,document.documentElement.scrollHeight-innerHeight))})`;let active=0,dist=1e9,ap=0;scenes.forEach((s,i)=>{const p=ease(prog(s,current));s.style.setProperty('--p',p.toFixed(4));if(i===2)s.style.setProperty('--bounce',`${Math.sin(p*Math.PI)*-70}px`);const d=Math.abs((s.offsetTop+s.offsetHeight/2)-(current+innerHeight/2));if(d<dist){dist=d;active=i;ap=p}});if(active!==last){dots.forEach((d,i)=>d.classList.toggle('active',i===active));last=active;if(active===6&&!partySeen){partySeen=true;burst(55)}}setActor(active,ap);if(Math.abs(target-current)>.1)raf=requestAnimationFrame(update);else raf=0}
 const schedule=()=>{if(!raf)raf=requestAnimationFrame(update)};addEventListener('scroll',schedule,{passive:true});addEventListener('resize',()=>{current=target=scrollY;schedule()});schedule();
 const layer=document.getElementById('confetti'),colors=['#e8898f','#91c2ca','#f0c361','#aebfa6','#8e6ca7'];function burst(n=90){if(reduced)return;for(let i=0;i<n;i++){const p=document.createElement('i');p.className='piece';p.style.left=Math.random()*100+'%';p.style.background=colors[i%colors.length];p.style.animationDuration=(2.8+Math.random()*3)+'s';p.style.animationDelay=Math.random()*.3+'s';layer.appendChild(p);setTimeout(()=>p.remove(),6500)}}document.getElementById('confettiBtn').onclick=()=>burst(130);
 const input=document.getElementById('photoUpload'),preview=document.getElementById('photoPreview'),placeholder=document.getElementById('placeholder');input.onchange=()=>{const f=input.files?.[0];if(!f)return;if(f.size>12*1024*1024){alert('Please choose an image under 12 MB.');input.value='';return}const r=new FileReader();r.onload=e=>{preview.src=e.target.result;preview.hidden=false;placeholder.hidden=true;burst(85)};r.readAsDataURL(f)};document.getElementById('replayBtn').onclick=()=>scrollTo({top:0,behavior:reduced?'auto':'smooth'});
 let ac=null,playing=false;const music=document.getElementById('musicBtn'),freq={G4:392,A4:440,B4:493.88,C5:523.25,D5:587.33,E5:659.25,F5:698.46,G5:783.99},mel=[['G4',.28],['G4',.18],['A4',.46],['G4',.46],['C5',.46],['B4',.8],['G4',.28],['G4',.18],['A4',.46],['G4',.46],['D5',.46],['C5',.8],['G4',.28],['G4',.18],['G5',.46],['E5',.46],['C5',.46],['B4',.46],['A4',.72],['F5',.28],['F5',.18],['E5',.46],['C5',.46],['D5',.46],['C5',.9]];music.onclick=async()=>{if(playing)return;playing=true;music.textContent='♪ Playing…';burst(120);ac=ac||new(window.AudioContext||window.webkitAudioContext)();await ac.resume();let t=ac.currentTime+.05;for(const[n,d]of mel){const o=ac.createOscillator(),g=ac.createGain();o.type='triangle';o.frequency.value=freq[n];g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.07,t+.03);g.gain.exponentialRampToValueAtTime(.0001,t+d-.02);o.connect(g).connect(ac.destination);o.start(t);o.stop(t+d);t+=d+.035}setTimeout(()=>{playing=false;music.textContent='▶ Play birthday tune'},(t-ac.currentTime)*1000+80)};
})();