// Character animation lives in the .riv; this page controls its inputs only.
const $=s=>document.querySelector(s),canvas=$('#character'),names=['Idle / breathing','Peeking','Looking around','Walking / trotting'];
let rig,inputs={},state=0,paused=false,token=0,frames=0,last=performance.now(),fps=0;
const target={lookX:50,lookY:50};
rive.RuntimeLoader.setWasmUrl('vendor/rive.wasm');
function set(n,v){if(inputs[n])inputs[n].value=v;}
function action(n){state=n;set('state',n);$('#state-label').textContent=names[n];$('#stage').classList.toggle('peeking',n===1);document.querySelectorAll('[data-state]').forEach(b=>b.classList.toggle('selected',+b.dataset.state===n));}
function sync(){set('moveSpeed',+$('#speed').value);set('scrollProgress',+$('#peek').value);set('hasHat',$('#hat').checked);set('blinkEnabled',$('#blink').checked);set('expression',+$('#expression').value);target.lookX=(+$('#look-x').value+1)*50;target.lookY=(+$('#look-y').value+1)*50;$('#speed-value').value=$('#speed').value+'%';$('#peek-value').value=$('#peek').value+'%';$('#x-value').value=(+$('#look-x').value).toFixed(2);$('#y-value').value=(+$('#look-y').value).toFixed(2);$('#stage').classList.toggle('guides',$('#debug').checked);}
rig=new rive.Rive({src:'../assets/character/production/marmalade-foundation.riv',canvas,autoplay:true,stateMachine:'Marmalade_Main',layout:new rive.Layout({fit:rive.Fit.Contain,alignment:rive.Alignment.Center}),onLoad(){inputs=Object.fromEntries(rig.stateMachineInputs('Marmalade_Main').map(i=>[i.name,i]));rig.resizeDrawingSurfaceToCanvas();sync();$('#status').textContent='Rive ready';if(matchMedia('(prefers-reduced-motion: reduce)').matches){paused=true;rig.pause();$('#pause').textContent='Play';}},onLoadError(e){$('#status').textContent='Rive failed to load';console.error(e);},onAdvance(){frames++;const now=performance.now();if(now-last>=1000){fps=Math.round(frames*1000/(now-last));frames=0;last=now;}}});
new ResizeObserver(()=>rig.resizeDrawingSurfaceToCanvas()).observe(canvas);
addEventListener('resize',()=>rig.resizeDrawingSurfaceToCanvas());
document.querySelectorAll('[data-state]').forEach(b=>b.onclick=()=>{token++;action(+b.dataset.state);});
document.querySelectorAll('input,select').forEach(el=>el.addEventListener('input',sync));$('#peek').addEventListener('input',()=>{token++;action(1);});
$('#pause').onclick=()=>{paused=!paused;paused?rig.pause():rig.play('Marmalade_Main');$('#pause').textContent=paused?'Play':'Pause';};
$('#mobile').onclick=()=>{$('.viewer').classList.toggle('phone');$('#mobile').textContent=$('.viewer').classList.contains('phone')?'Full frame':'Phone frame';};
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function ramp(from,to,ms,t){const start=performance.now();while(token===t){const p=Math.min(1,(performance.now()-start)/ms),ease=p*p*(3-2*p);$('#peek').value=from+(to-from)*ease;sync();if(p===1)return;await new Promise(requestAnimationFrame);}}
async function test(which){const t=++token;$('#test-status').textContent='Running '+which+'…';if(paused)$('#pause').click();if(which==='walk'){action(0);await wait(800);if(t!==token)return;action(3);await wait(2600);if(t!==token)return;action(0);}else{action(1);$('#peek').value=0;sync();await wait(600);if(t!==token)return;await ramp(0,100,1700,t);await wait(900);if(t!==token)return;if(which==='reverse'){await ramp(100,0,1700,t);await ramp(0,100,1700,t);}else action(2);}if(t===token)$('#test-status').textContent='Sequence complete — inspect another transition.';}
$('#peek-test').onclick=()=>test('peek');$('#walk-test').onclick=()=>test('walk');$('#reverse-test').onclick=()=>test('reverse');
function gaze(v){action(2);$('#look-x').value=v;sync();}$('#gaze-left').onclick=()=>gaze(-1);$('#gaze-right').onclick=()=>gaze(1);
$('#reset').onclick=()=>{token++;action(0);$('#look-x').value=0;$('#look-y').value=0;$('#peek').value=100;$('#speed').value=0;$('#expression').value=0;$('#hat').checked=false;$('#track').checked=false;$('#blink').checked=true;sync();};
canvas.addEventListener('pointermove',e=>{if(!$('#track').checked)return;const r=canvas.getBoundingClientRect();$('#look-x').value=Math.max(-1,Math.min(1,(e.clientX-r.left)/r.width*2-1));$('#look-y').value=Math.max(-1,Math.min(1,(e.clientY-r.top)/r.height*2-1));sync();});
let lastRead=0;function tick(now){for(const n of ['lookX','lookY'])if(inputs[n])set(n,inputs[n].value+(target[n]-inputs[n].value)*.12);if(now-lastRead>200){lastRead=now;$('#readout').textContent=`Marmalade_Main / ${names[state]}\n${Object.entries(inputs).map(([n,i])=>`${n}: ${typeof i.value==='number'?i.value.toFixed(2):i.value}`).join('  ·  ')}\n${paused?'Paused':fps+' rendered advances/s'} · canvas ${canvas.width} × ${canvas.height} · DPR ${devicePixelRatio.toFixed(2)}`;}requestAnimationFrame(tick);}requestAnimationFrame(tick);
document.addEventListener('visibilitychange',()=>{if(document.hidden)rig.stopRendering();else if(!paused)rig.startRendering();});addEventListener('pagehide',()=>rig.cleanup());
